name: kurban_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  url_launcher: ^6.0.0
  file_picker: ^5.0.0
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.2.3
  pdf: ^3.7.0
  printing: ^5.12.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "android/app/src/main/res/polygon_style_big_sheep_ram_an.jpeg"
